application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /script
  static_dir: script

- url: /css
  static_dir: styles

- url: /src
  static_dir: src

- url: /
  static_files: index.html
  upload: index.html
